## Names

We have previously studied how to look up values in vectors by *index* - for example, to fetch the third element of the vector `my.vec`:

In [1]:
my.vec <- c("hello", "there", "friend")
my.vec[3]

[1] "friend"

Yet another powerful feature provided by R is the ability to label and access vector elements by *name*, not just by *index*. To accomplish this, we can preceed each argument to the `c` function with the name by which we wish to refer to it:

In [2]:
account.balances <- c("bill gates" = 1000000, "joe sixpack" = 1000, "bob cratchit" = -10)

We can see that now these names are each attached to the appropriate entry in the vector:

In [3]:
print(account.balances)

  bill gates  joe sixpack bob cratchit
       1e+06        1e+03       -1e+01

Now, if we want to look up the account balance for `"bob cratchit"`, we can simply access it directly using the same `[...]` operator that we used for accessing elements by numerical index:

In [6]:
print(str(account.balances))
account.balances["bob cratchit"]

 Named num [1:3] 1e+06 1e+03 -1e+01
 - attr(*, "names")= chr [1:3] "bill gates" "joe sixpack" "bob cratchit"
NULL

bob cratchit
         -10

<span style="color:blue;font-weight:bold">Exercise</span>: Create a vector named `country.codes` containing the following elements: 

* `1`
* `60`
* `86`

These elements should be labeled with the following names (in the same order):

* `"USA"` 
* `"Malaysia"`
* `"China"`

In [7]:
# delete this entire line and replace it with your code

country.codes <- c("USA"=1, "Malaysia"=60, "China"=86)

In [8]:
check.variable.value("country.codes", c("USA" = 1, "Malaysia" = 60, "China" = 86))
success()

## Setting Names on Existing Vectors

Suppose that we have already created a vector of `cars`, and we would like to attach the names of the car owners to each car. We can easily do this even after the `cars` vector has already been created using the `names(...)` function:

In [8]:
cars <- c("Nightrider", "1970 Dodge Charger R/T", "Lambo")
names(cars) <- c("David Hasselhoff", "Vin Diesel", "Bitcoin HODLer")
print(cars)

        David Hasselhoff               Vin Diesel           Bitcoin HODLer
            "Nightrider" "1970 Dodge Charger R/T"                  "Lambo"

We can then access the vector elements directly by name, as before:

In [9]:
cars["Vin Diesel"]

              Vin Diesel
"1970 Dodge Charger R/T"

## Un-Naming Vectors

Remember that everything in R is a vector - expressions like `cars["Vin Diesel"]` yield one-element vectors:

In [10]:
length(cars["Vin Diesel"])

[1] 1

Notice that the name `Vin Diesel` is printed along with the corresponding value of `cars["Vin Diesel"]`:

In [11]:
cars["Vin Diesel"]

              Vin Diesel
"1970 Dodge Charger R/T"

This is because the name `"Vin Diesel"` is still associated with that one-element vector:

In [12]:
names(cars["Vin Diesel"])

[1] "Vin Diesel"

To remove the name and get back a single, raw number, use the `unname()` function:

In [13]:
unname(cars["Vin Diesel"])

[1] "1970 Dodge Charger R/T"

# Row and  Column Names

Data frame rows and columns can have names set and read in the same manner as vector names - let's work with the `cement` dataset again as an example:

In [14]:
cement.df <- read.csv("data/cement.csv")
head(cement.df)

  gdp.trillions cement.imports.billions
1 2.000000      0.4019249
2 2.051320      0.3957969
3 2.117807      0.4203297
4 2.216580      0.4595390
5 2.233002      0.4397102
6 2.388326      0.4980864

We can label each row with a name using `rownames` - for example, we could associate each row with a date:

In [15]:
my.dates <- c("01/01/1992", 
              "02/01/1992",
              "03/01/1992",
              "04/01/1992",
              "05/01/1992",
              "06/01/1992",
              "07/01/1992",
              "08/01/1992",
              "09/01/1992",
              "10/01/1992")
rownames(cement.df) <- my.dates
head(cement.df)

           gdp.trillions cement.imports.billions
01/01/1992 2.000000      0.4019249
02/01/1992 2.051320      0.3957969
03/01/1992 2.117807      0.4203297
04/01/1992 2.216580      0.4595390
05/01/1992 2.233002      0.4397102
06/01/1992 2.388326      0.4980864

Notice that the row names are now listed to on the left-hand-side. The column names of our data frame are usually already set and visible:

In [16]:
colnames(cement.df)

[1] "gdp.trillions"           "cement.imports.billions"

We can change them in the expected way, just like all other kinds of names:

In [17]:
colnames(cement.df) <- c("col1", "col2")
head(cement.df)

           col1     col2
01/01/1992 2.000000 0.4019249
02/01/1992 2.051320 0.3957969
03/01/1992 2.117807 0.4203297
04/01/1992 2.216580 0.4595390
05/01/1992 2.233002 0.4397102
06/01/1992 2.388326 0.4980864

<span style="color:blue;font-weight:bold">Exercise</span>: Set the `rownames` of `cement.df` to be the numbers `1` through `10` (hint: you can just use the vector `1:10` directly), then set the `colnames` to be `first.col` and `second.col`:

In [18]:
# delete this entire line and replace it with your code

rownames(cement.df) <- 1:10
colnames(cement.df) <- c("first.col", "second.col")

In [19]:
assert.true(all(rownames(cement.df) == 1:10), "<code>rownames(...)</code> not set correctly.")
assert.true(all(colnames(cement.df) == c("first.col", "second.col")), "<code>colnames(...)</code> not set correctly.")
success()